apiVersion: apps/v1
kind: Deployment
metadata:
  name: cities
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      run: cities
  template:
    metadata:
      labels:
        run: cities
    spec:
      containers:
      - image: gcr.io/proud-effect-284706/cities
        imagePullPolicy: Always
        name: cities
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cities
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: cities
  type: LoadBalancer